name: flutter_bloc_learn
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  #data
  shared_preferences: ^2.3.2
  path_provider: ^2.1.5
  #State Management
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  provider: ^6.1.2
  meta: ^1.15.0
  #
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  collection: ^1.18.0
  #design
  lottie: ^3.1.3
  flutter_svg: ^2.0.16
  #firebase
  firebase_core: ^3.8.0
  cloud_firestore: ^5.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  json_serializable: ^6.8.0

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/lottie/lottieee.json
